#### NLP with ML

In [183]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [184]:
df  = pd.read_csv("train.txt", sep =";",header =None,names=["text","emotion"])

In [185]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [186]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [187]:
unique_emotion = df["emotion"].unique()

In [188]:
emotion_numbers = {}
i=0
for emo in unique_emotion:
    emotion_numbers[emo] = i
    i +=1
df["emotion"] = df["emotion"].map(emotion_numbers)

In [189]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [190]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [191]:
#lowercasing 
df["text"] = df["text"].apply(lambda x:x.lower())

In [192]:
#remove punctuation 
import string 
def remove_punctuation(text):
    return text.translate(str.maketrans(" "," ",string.punctuation))

In [193]:
 df["text"]= df["text"].apply(remove_punctuation)

In [194]:
#remove numbers 
def remove_numbers(text):
    new = ""
    for i in text:
        if not i.isdigit():
            new = new +i
     
    return new
        
df["text"] = df["text"].apply(remove_numbers)

In [195]:
#removing urlks/links 
import re

def remove_urls(text):
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    
 return text
 
df["text"] = df["text"].apply(remove_urls)

IndentationError: unindent does not match any outer indentation level (<string>, line 8)

In [124]:
#removing emojis and special character 
def remove_emojis(text):
    new = ""
    for i in text:
        if not i.isascii():
            new = new +i
            
    return new 
        
df["text"] = df["text"].apply(remove_emojis)

In [125]:
import sys
!{sys.executable} -m pip install nltk

Requirement already satisfied: nltk in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.10.3)
Requirement already satisfied: defusedxml in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from nltk) (8.4.2)
Requirement already satisfied: joblib in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from nltk) (2026.7.19)
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from nltk) (4.70.0)

In [126]:
import nltk 
from nltk.corpus import stopwords
from  nltk.tokenize import word_tokenize

In [127]:
nltk.download("punkt")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to /Users/tanujpant/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/tanujpant/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [197]:
stop_words = set(stopwords.words("english"))
print(list(stop_words)[:10])

['shan', 'few', 'other', "i'd", 'from', 'yourselves', 'above', 'both', 'your', 's']

In [198]:

def remove(text):
    if text is None:
        return ""

    words = word_tokenize(str(text))
    cleaned = []

    for i in words:
        if i.lower() not in stop_words:
            cleaned.append(i)

    return " ".join(cleaned)

In [206]:
textcase = "i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake"

print(remove(textcase))

go feeling hopeless damned hopeful around someone cares awake

In [175]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/tanujpant/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [202]:
df["text"] = df["text"].apply(remove)

In [203]:
df["text"]

0                                    didnt feel humiliated
1        go feeling hopeless damned hopeful around some...
2                im grabbing minute post feel greedy wrong
3        ever feeling nostalgic fireplace know still pr...
4                                          feeling grouchy
                               ...
15995        brief time beanbag said anna feel like beaten
15996    turning feel pathetic still waiting tables sub...
15997                             feel strong good overall
15998                       feel like rude comment im glad
15999                         know lot feel stupid portray
Name: text, Length: 16000, dtype: str

In [204]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [205]:
df.loc[1]["text"]

'go feeling hopeless damned hopeful around someone cares awake'