#### pivot tables

In [2]:
import numpy as np 
import pandas as pd

In [3]:
data= {
"Date": pd.date_range("2023-01-01",periods=20),
"Product":["A","B","C","D"] * 5,
"Region":["East","West","North","South","East","West","North","South","East","West","North","South","East","West","North","South","East","West","North","South"],
"Sales":np.random.randint(100,1000,20),
"Units":np.random.randint(10,100,20),
"Rep":["john","Mary","Bob","Alice","john","Mary","Bob","Alice","john","Mary","Bob","Alice","john","Mary","Bob","Alice","john","Mary","Bob","Alice"]

}
df= pd.DataFrame(data)
df["Month"]= df["Date"].dt.month_name()
df["Quarter"]= "Q" + df["Date"].dt.quarter.astype(str)

In [4]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    931     93   john  January      Q1
1  2023-01-02       B   West    467     24   Mary  January      Q1
2  2023-01-03       C  North    365     65    Bob  January      Q1
3  2023-01-04       D  South    875     32  Alice  January      Q1
4  2023-01-05       A   East    880     95   john  January      Q1
5  2023-01-06       B   West    194     84   Mary  January      Q1
6  2023-01-07       C  North    523     88    Bob  January      Q1
7  2023-01-08       D  South    987     17  Alice  January      Q1
8  2023-01-09       A   East    260     26   john  January      Q1
9  2023-01-10       B   West    751     58   Mary  January      Q1
10 2023-01-11       C  North    438     20    Bob  January      Q1
11 2023-01-12       D  South    615     74  Alice  January      Q1
12 2023-01-13       A   East    322     30   john  January      Q1
13 2023-01-14       B   West    580     64   Mary  January      Q1
14 2023-01-15       C  North    731     44    Bob  January      Q1
15 2023-01-16       D  South    634     26  Alice  January      Q1
16 2023-01-17       A   East    427     51   john  January      Q1
17 2023-01-18       B   West    806     11   Mary  January      Q1
18 2023-01-19       C  North    695     16    Bob  January      Q1
19 2023-01-20       D  South    214     90  Alice  January      Q1

In [7]:
pd.pivot_table(df,values="Sales", index="Region",columns="Product", aggfunc="median")
# by default here values are the mean of all values we can also change it by giving parameter (aggfunc) , pivot tables is widely used for making cluster heat maps

Product      A      B      C      D
Region
East     427.0    NaN    NaN    NaN
North      NaN    NaN  523.0    NaN
South      NaN    NaN    NaN  634.0
West       NaN  580.0    NaN    NaN

In [8]:
pivot2= pd.pivot_table(df,values=["Sales","Units"], index="Region",columns="Product", aggfunc="median")
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     427.0    NaN    NaN    NaN  51.0   NaN   NaN   NaN
North      NaN    NaN  523.0    NaN   NaN   NaN  44.0   NaN
South      NaN    NaN    NaN  634.0   NaN   NaN   NaN  32.0
West       NaN  580.0    NaN    NaN   NaN  58.0   NaN   NaN

###### cross tabs

In [9]:
# cross tabs are same as pivot tables ,the difference is that cross tabs uses counting functions while pivot tables used aggregation function 
pd.crosstab(df["Region"],df["Product"])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

#####  DataFrames Basic operations

In [10]:
df1= pd.DataFrame({
    "A": [1,2,3,4,5],
    "B":[10,20,30,40,50],
    "C": [100,200,300,400,500]
})

In [11]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [12]:
df1.shape

(5, 3)

In [13]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [14]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [15]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [16]:
df1["A"] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

###### Applying functions

In [17]:
# we can create functions 
def square(x):
    return x**2

In [18]:
# by this method we can apply function to any column of dataframes 
df1["B"].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [19]:
# to changes on original dataframes 
df1["B"]=df1["B"].apply(square)

In [20]:
df1

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500

In [21]:
# we can also add extra columns by performing function 
df1["D"]=df1["B"].apply(square)

In [22]:
df1

   A     B    C        D
0  1   100  100    10000
1  2   400  200   160000
2  3   900  300   810000
3  4  1600  400  2560000
4  5  2500  500  6250000